name: Build wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - fix
  release:
    types:
      - published
  schedule:
      - cron: '45 4 * * *'

jobs:
  get_urls:
    name: Fetch sdist URLs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    outputs:
      urls: ${{ steps.get-urls.outputs.urls }}

    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          set -e
          pip install -r requirements.txt

      - name: Fetch URLs
        id: get-urls
        run: |
          set -e
          curl -LsS "https://github.com/$GITHUB_REPOSITORY/releases/latest/download/wheels.tar.gz" | tar --wildcards -ztf - '*.whl' > cached.txt
          output=$(python get-urls.py)
          echo "urls=$output" >> "$GITHUB_OUTPUT"

          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          if git diff packages.json5 | grep -q .; then
            git add packages.json5
            git commit -m 'Update package list'
          fi

      - name: Push updated package list
        uses: ad-m/github-push-action@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  build_wheels:
    name: Build wheels
    needs: [get_urls]
    runs-on: ubuntu-latest
    if: needs.get_urls.outputs.urls != '[]'
    strategy:
      matrix:
        url: ${{ fromJson(needs.get_urls.outputs.urls) }}

    steps:
      - uses: actions/checkout@v7

      - name: Install Android command line tools
        id: android-sdk
        run: |
          set -e

          curl -LsS -o android.zip "https://dl.google.com/android/repository/commandlinetools-linux-15859902_latest.zip"
          mkdir -p android-sdk/cmdline-tools
          (cd android-sdk/cmdline-tools && unzip ../../android.zip)
          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest

      - name: Prepare sdist
        id: prepare-sdist
        env:
          URL: ${{ matrix.url }}
        run: |
          set -e
          # get rid of this, it screws `git apply`
          rm -fr .git
          mkdir -p build
          cd build

          if grep -q '^git:' <<< "$URL"; then
            # special case
            eval "$(sed -e 's/^git:/dest=/' -e 's/:/ tag=/' -e 's/:/ url="/' -e 's/$/"/' <<< "$URL")"
            echo "Cloning $url to $dest"
            git clone --depth 1 --branch "$tag" --recurse-submodules "$url" "$dest"
          else
            curl -LsS -O "$URL"
            file=$(echo *)
            echo "Unpacking $file"
            tar -axf "$file"
            rm "$file"
          fi

          # split name and version
          eval "package=$(echo * | tr '[:upper:]' '[:lower:]' | sed 's/-/ version=/')"
          mv * "$package"
          cd "$package"
          for patch_name in "$package-$version" "$package"; do
            if [ -f "../../patches/$patch_name.patch" ]; then
              echo "Applying $patch_name.patch"
              git apply "../../patches/$patch_name.patch"
              break
            fi
          done
          echo "package=$package" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.2.0
        with:
          package-dir: build/${{ steps.prepare-sdist.outputs.package }}
          extras: uv
        env:
          CIBW_PLATFORM: android
          CIBW_ARCHS_ANDROID: arm64_v8a
          CIBW_REPAIR_WHEEL_COMMAND_ANDROID: "LDPATHS={ldpaths} DEST_DIR={dest_dir} WHEEL={wheel} ./auditwheel.sh"
          CIBW_BUILD_FRONTEND: "build[uv]"
          CIBW_ENVIRONMENT_ANDROID: "LDSHARED=${{ github.workspace }}/ldshared.sh"

          ANDROID_HOME: "${{ github.workspace }}/android-sdk"

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.prepare-sdist.outputs.package }}-${{ steps.prepare-sdist.outputs.version }}
          path: ./wheelhouse/*.whl

  release:
    name: Create release
    needs: [build_wheels]
    if: github.ref_name == 'main' || (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Pack final archive
        run: |
          set -e
          mkdir wheels
          cd artifacts
          for file in *; do
            package=$(sed 's/-[^$]*$//' <<< "$file" | sed -E 's/[-_.]+/-/g')
            mkdir -p "../wheels/$package"
            if [ -d "$file" ]; then
              mv "$file/"* "../wheels/$package"
            else
              mv "$file" "../wheels/$package"
            fi
          done
          cd ../wheels
          curl -LsS "https://github.com/$GITHUB_REPOSITORY/releases/latest/download/wheels.tar.gz" | tar -zxkf -
          zip -r ../wheels.zip *
          tar -acf ../wheels.tar.gz *

      - name: Create release
        uses: softprops/action-gh-release@v3.0.2
        with:
          tag_name: v0.0.1
          files: |
            wheels.zip
            wheels.tar.gz
